orders/urls.py
from django.urls import path

from .views import (
    OrderListView, checkout, add_to_cart, remove_from_cart, remove_from_checkout,
    process_payment, payment_success, payment_failed, coupon, wishlist_view,
    remove_from_wishlist, add_to_wishlist, update_cart_item_quantity # Added new view
)
from .api import CartDetailCreateAPI , OrderListAPI , OrderDetailsAPI , CreateOrderAPI , ApplyCouponAPI



app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='order_list'),
    path('checkout/', checkout, name='checkout'),
    path('coupon/', coupon, name='coupon'),
    path('checkout/payment/', process_payment, name='process_payment'),
    path('checkout/payment/success', payment_success),
    path('checkout/payment/failed', payment_failed),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:id>', remove_from_cart, name='remove_from_cart'),
    path('remove-from-checkout/<int:id>', remove_from_checkout, name='remove_from_checkout'),
    path('wishlist/', wishlist_view, name='wishlist'),
    path('wishlist/remove/<int:pk>/', remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/add/<int:product_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('cart/update-quantity/', update_cart_item_quantity, name='update_cart_item_quantity'), # Added URL for AJAX update

    # api
    path('api/list/<str:username>' ,OrderListAPI.as_view(), name='OrderListAPI'),
    path('api/list/<str:username>/create-order' ,CreateOrderAPI.as_view(), name='CreateOrderAPI'),
    path('api/list/<str:username>/<int:pk>' ,OrderDetailsAPI.as_view(), name='OrderDetailsAPI'),
    path('api/<str:username>/cart' ,CartDetailCreateAPI.as_view(), name='CartDetailCreateAPI'),
    path('api/<str:username>/cart/apply-coupon' ,ApplyCouponAPI.as_view(), name='CartDetailCreateAPI'),
]

products/urls.py
from django.urls import path
from .views import BulkProductUploadAPIView, recommended_products_view, ProductDetails, ProductList, BrandList, BrandDetails, queryset_debug , product_search , product_filter , product_filter_by_flag , send_emails , add_review 
from .api import  product_list_api , product_detail_api , ProductListAPI , ProductDetailAPI , BrandListAPI , BrandDetailAPI

app_name = 'products'

urlpatterns = [
    path('brands/', BrandList.as_view(), name='brand_list'),
    path('search/', product_search, name='product_search'),
    path('filter/', product_filter, name='product_filter'),
    path('<slug:slug>/add-review', add_review, name='add_review'),
    path('filter-by-tags/', product_filter_by_flag, name='product_filter_by_tags'),
    path('', ProductList.as_view(), name='product_list'),
    path('debug/', queryset_debug, name='queryset_debug'),  # Debugging tool for testing queryset performance.
    path('send-email/', send_emails, name='send_emails'),  # celery with radis
    path('<slug:slug>/', ProductDetails.as_view(), name='product_detail'),
    path('brands/<slug:slug>/', BrandDetails.as_view(), name='brand_detail'),

    #api function
    path('api/list', product_list_api, name='product_api_list'),
    path('api/list/<int:product_name>', product_detail_api , name='product_detail_api'),

    path('api/recommendations/', recommended_products_view, name='recommendations'),


    #Api genaric views
    path('api/genariclist', ProductListAPI.as_view()),
    path('api/genariclist/<int:pk>', ProductDetailAPI.as_view()),
    path('api/brandlist', BrandListAPI.as_view()),
    path('api/brandlist/<int:pk>', BrandDetailAPI.as_view()),

    path('api/products/bulk-upload/', BulkProductUploadAPIView.as_view(), name='bulk-product-upload'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# swagger
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # application
    path('', include('userauths.urls')),
    path('management/', include('administration.urls')),
    path('', include('settings.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),

    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    # rosetta translation
    path('rosetta/', include('rosetta.urls')),
    # Swagger/OpenAPI schema
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.urls import re_path
from django.views.decorators.csrf import csrf_exempt

from .core.views import jwks
from .graphql.api import backend, schema
from .graphql.views import GraphQLView
from .plugins.views import (
    handle_global_plugin_webhook,
    handle_plugin_per_channel_webhook,
    handle_plugin_webhook,
)
from .product.views import digital_product
from .thumbnail.views import handle_thumbnail

urlpatterns = [
    re_path(
        r"^graphql/$",
        csrf_exempt(GraphQLView.as_view(backend=backend, schema=schema)),
        name="api",
    ),
    re_path(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        digital_product,
        name="digital-product",
    ),
    re_path(
        r"^plugins/channel/(?P<channel_slug>[.0-9A-Za-z_\-]+)/"
        r"(?P<plugin_id>[.0-9A-Za-z_\-]+)/",
        handle_plugin_per_channel_webhook,
        name="plugins-per-channel",
    ),
    re_path(
        r"^plugins/global/(?P<plugin_id>[.0-9A-Za-z_\-]+)/",
        handle_global_plugin_webhook,
        name="plugins-global",
    ),
    re_path(
        r"^plugins/(?P<plugin_id>[.0-9A-Za-z_\-]+)/",
        handle_plugin_webhook,
        name="plugins",
    ),
    re_path(
        (
            r"^thumbnail/(?P<instance_id>[.0-9A-Za-z_=\-]+)/(?P<size>\d+)/"
            r"(?:(?P<format>[a-zA-Z]+)/)?"
        ),
        handle_thumbnail,
        name="thumbnail",
    ),
    re_path(r"^\.well-known/jwks.json$", jwks, name="jwks"),
]

if settings.DEBUG:
    from .core import views

    urlpatterns += static("/media/", document_root=settings.MEDIA_ROOT) + [
        re_path(r"^static/(?P<path>.*)$", serve),
        re_path(r"^$", views.home, name="home"),
    ]

saleor/saleor/attribute/models/product.py
from django.contrib.postgres.indexes import BTreeIndex
from django.db import models

from ...core.models import SortableModel
from ...product.models import Product, ProductType
from .base import AssociatedAttributeManager


class AssignedProductAttributeValue(SortableModel):
    value = models.ForeignKey(
        "AttributeValue",
        on_delete=models.CASCADE,
        related_name="productvalueassignment",
    )
    product = models.ForeignKey(
        Product,
        related_name="attributevalues",
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        db_index=False,
    )

    class Meta:
        unique_together = (("value", "product"),)
        ordering = ("sort_order", "pk")
        indexes = [
            BTreeIndex(fields=["product"], name="assignedprodattrval_product_idx")
        ]

    def get_ordering_queryset(self):
        return self.product.attributevalues.all()


class AttributeProduct(SortableModel):
    attribute = models.ForeignKey(
        "Attribute", related_name="attributeproduct", on_delete=models.CASCADE
    )
    product_type = models.ForeignKey(
        ProductType, related_name="attributeproduct", on_delete=models.CASCADE
    )

    objects = AssociatedAttributeManager()

    class Meta:
        unique_together = (("attribute", "product_type"),)
        ordering = ("sort_order", "pk")

    def get_ordering_queryset(self):
        return self.product_type.attributeproduct.all()

products/views.py
from django.shortcuts import render , redirect
from django.views.generic import ListView , DetailView
from django.db.models import Q , F , Value , Count
from django.db.models.aggregates import Max,Min,Count,Avg,Sum
from django.views.decorators.cache import cache_page # python raises py caching exceptions
from django.http import JsonResponse
from django.template.loader import render_to_string



from .models import Product, Brand, ProductImage, Review
from .task import send_email

from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import ProductSerializer


from .recommendation_engine import get_recommendations_for_user
from .serializers import ProductListSerializers  # existing serializer

class BulkProductUploadAPIView(APIView):
    permission_classes = [AllowAny]  # 👈 add this
    def post(self, request, *args, **kwargs):
        products_data = request.data if isinstance(request.data, list) else [request.data]
        serializer = ProductSerializer(data=products_data, many=True)
        if serializer.is_valid():
            serializer.save()
            return Response({"message": "Products added successfully."}, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def recommended_products_view(request):
    user_id = request.user.id if request.user.is_authenticated else None
    recommended_products = get_recommendations_for_user(user_id)
    serializer = ProductListSerializers(recommended_products, many=True)
    return JsonResponse(serializer.data, safe=False)


# class RecommendedProductsAPIView(APIView):
#     permission_classes = [AllowAny]

#     def get(self, request):
#         user_id = request.user.id
#         recommended_products = get_recommendations_for_user(user_id)
#         serializer = ProductListSerializers(recommended_products, many=True)
#         return Response(serializer.data)

@cache_page(60 * 1)
def queryset_debug(request):
    
    # data = Product.objects.all()
    
    # data = Product.objects.filter(price__gt=80, quantity__lt=10)  #and
    
    # data = Product.objects.filter(Q(price__gt=80) & Q(quantity__lt=10))  #or
    
    # data = Product.objects.annotate(price_with_tax=F('price')*1.2) # add new tower

    data = Product.objects.all()

    
    return render(request, 'products/queryset_debug.html', {'data': data})



def send_emails(request):
    if request.method == 'GET':
        send_email.delay()  
        return render(request, 'products/send_email.html')

    elif request.method == 'POST':
        progress = cache.get('email_progress', 'No progress yet.')
        sent_emails = cache.get('sent_emails', [])
        return JsonResponse({'status': progress, 'sent_emails': sent_emails})



class ProductList(ListView):
    model = Product
    paginate_by = 30
    ordering = ['-id']



class ProductDetails(DetailView):
    model = Product
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context["reviews"] = Review.objects.filter(product=product)
        context["average_rating"] = product.average_rating
        context["rate_products"] = Product.objects.filter(brand=product.brand)
        return context
    


class BrandList(ListView):
    model = Brand
    queryset = Brand.objects.annotate(products_count=Count('product_name'))
    paginate_by = 20
    ordering = ['-id']



class BrandDetails(ListView):
    model = Product
    paginate_by = 20
    template_name = 'products/brand_detail.html'
    
    def get_queryset(self):
        brand = Brand.objects.get(slug=self.kwargs['slug'])
        return super().get_queryset().filter(brand=brand)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        brand = Brand.objects.annotate(products_count=Count('product_name')).get(slug=self.kwargs['slug'])
        context["brand"] = brand  

        return context 




# search and filter with category
def product_search(request):
    query = request.GET.get('q', '')
    if query:
        # Search products by name, description, or SKU
        products = Product.objects.filter(
            Q(name__icontains=query) | 
            Q(descripition__icontains=query) |
            Q(sku__icontains=query) |
            Q(tags__name__icontains=query)
        ).distinct()
    else:
        products = Product.objects.all()
    
    return render(request, 'products/product_search.html', {'product_list': products})



def product_filter(request):
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')

    products = Product.objects.all()
    if min_price:
        products = products.filter(price__gte=float(min_price))
    if max_price:
        products = products.filter(price__lte=float(max_price))
    
    return render(request, 'products/product_filter.html', {'products': products})



def product_filter_by_flag(request):
    tags = request.GET.getlist('tags')
    products = Product.objects.all()

    if tags:
        products = products.filter(flag__in=tags)

    return render(request, 'products/product_filter_by_tag.html', {'products': products})




def add_review(request,slug):
    product = Product.objects.get(slug=slug)

    rate = request.POST['rate']  # rate = request.POST.get('rate') , request.GET['rate'] = request.POST.get('rate)
    review = request.POST['review']

    Review.objects.create(
        product=product,
        rate=rate,
        review=review,
        user=request.user,
    )

    # review
    reviews = Review.objects.filter(product=product)
    html = render_to_string('include/reviews_include.html',{'reviews':reviews , request:request})
    return JsonResponse({'result': html})

    # return redirect(f'/products/{product.slug}')

saleor/saleor/product/views.py
import mimetypes
import os

from django.conf import settings
from django.http import FileResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404

from .models import DigitalContentUrl
from .utils.digital_products import (
    digital_content_url_is_valid,
    increment_download_count,
)


def digital_product(request, token: str) -> FileResponse | HttpResponseNotFound:
    """Return the direct download link to content if given token is still valid."""

    qs = DigitalContentUrl.objects.using(
        settings.DATABASE_CONNECTION_REPLICA_NAME
    ).prefetch_related("line__order__user")
    content_url = get_object_or_404(qs, token=token)  # type: DigitalContentUrl
    if not digital_content_url_is_valid(content_url):
        return HttpResponseNotFound("Url is not valid anymore")

    digital_content = content_url.content
    digital_content.content_file.open()
    opened_file = digital_content.content_file.file
    filename = os.path.basename(digital_content.content_file.name)
    file_expr = f'filename="{filename}"'

    content_type = mimetypes.guess_type(str(filename))[0]
    response = FileResponse(opened_file)
    response["Content-Length"] = digital_content.content_file.size

    response["Content-Type"] = str(content_type)
    response["Content-Disposition"] = f"attachment; {file_expr}"

    increment_download_count(content_url)
    return response

products/templates/products/brand_detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    {% if LANGUAGE_CODE == 'en' %}
        <link rel="stylesheet" href="{% static 'en/css/brand-single.css' %}">
    {% else %}
        <link rel="stylesheet" href="{% static 'ar/css/brand-single.css' %}">
    {% endif %}
{% endblock css %}
    
{% block boody %}


        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'products:brand_list' %}">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================BANNER PART END=======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" style="width: 200px; height: 200px;" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            {% comment %} <ul>
                <i class="icofont-star {% if brand.avg_rate > 0 %}active{% endif %}"></i>
                <i class="icofont-star {% if brand.avg_rate > 1 %}active{% endif %}"></i>
                <i class="icofont-star {% if brand.avg_rate > 2 %}active{% endif %}"></i>
                <i class="icofont-star {% if brand.avg_rate > 3 %}active{% endif %}"></i>
                <i class="icofont-star {% if brand.avg_rate > 4 %}active{% endif %}"></i>
                <a href="#">(({{brand.review_product.all|length}})</a>
            </ul> {% endcomment %}
            <p>({{brand.products_count}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">

                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                    
                    {% for object in object_list %}
 
                        <div class="col">
                            <div class="product-card">
                                <div class="product-media">
                                    <div class="product-label">
                                        <label class="label-text new">{{object.flag}}</label>
                                    </div>
                                    <a class="product-image" href="{% url 'products:product_detail' object.slug %}">
                                        <img src="{{object.image.url}}" style="width: 257px; height: 257px;" alt="product">
                                    </a>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating">
                                        <i class="icofont-star {% if object.avg_rate > 0 %}active{% endif %}"></i>
                                        <i class="icofont-star {% if object.avg_rate > 1 %}active{% endif %}"></i>
                                        <i class="icofont-star {% if object.avg_rate > 2 %}active{% endif %}"></i>
                                        <i class="icofont-star {% if object.avg_rate > 3 %}active{% endif %}"></i>
                                        <i class="icofont-star {% if object.avg_rate > 4 %}active{% endif %}"></i>
                                        <a href="{% url 'products:product_detail' object.slug %}">({{object.review_product.all|length}})</a>
                                    </div>
                                    <h6 class="product-name">
                                        <a href="{% url 'products:product_detail' object.slug %}">{{object}}</a>
                                    </h6>
                                    <h6 class="product-price">
                                        <span>{{object.price}} DT</span>
                                    </h6>
                                    
                                    <div class="product-action">
                                        <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                        <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                        <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                        

                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                {% comment %} before {% endcomment %}
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>
                                {% endif %}
                                    
                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        {% comment %} The page is on it {% endcomment %}
                                        <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                    {% elif  i > page_obj.number|add:'-4'  and i < page_obj.number|add:'4' %}
                                        {% comment %} The Pages after me {% endcomment %}
                                        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                    
                                {% comment %} After {% endcomment %}
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                            <i class="fas fa-long-arrow-alt-right"></i>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
{% endblock boody %}

products/templates/products/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    {% if LANGUAGE_CODE == 'en' %}
        <link rel="stylesheet" href="{% static 'en/css/brand-list.css' %}">
    {% else %}
        <link rel="stylesheet" href="{% static 'ar/css/brand-list.css' %}">
    {% endif %}
{% endblock css %}
    
{% block boody %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                    {% for brand in brand_list %}
                        <div class="col all vegetables">
                            <div class="brand-wrap">
                                <div class="brand-media">

                                    {% if brand.image %}
                                        <img src="{{ brand.image.url }}" style="width: 150px; height: 150px;" alt="brand">
                                    {% else %}
                                        <img src="/media/sddefault.jpg" style="width: 150px; height: 150px;" alt="default brand image">
                                    {% endif %}

                                    <div class="brand-overlay">
                                        <a href="{% url 'products:brand_detail' brand.slug %}"><i class="fas fa-link"></i></a>
                                    </div>
                                </div>
                                <div class="brand-meta">
                                    <h4>{{brand}}</h4>
                                    <p>( {{brand.products_count}} items)</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">
                    
                                    {% comment %} before {% endcomment %}
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                    
                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            {% comment %} The page is on it {% endcomment %}
                                            <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                        {% elif  i > page_obj.number|add:'-4'  and i < page_obj.number|add:'4' %}
                                            {% comment %} The Pages after me {% endcomment %}
                                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    
                                    {% comment %} After {% endcomment %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->
{% endblock boody %}